import { db } from "@workspace/db";
import { productsTable as products, couponsTable as coupons, categoriesTable as categories } from "@workspace/db/schema";

const sampleCategories = [
  { name: "Moisturizers", slug: "moisturizers", icon: "💧", displayOrder: 1 },
  { name: "Serums",       slug: "serums",       icon: "✨", displayOrder: 2 },
  { name: "Sunscreen",    slug: "sunscreen",    icon: "☀️", displayOrder: 3 },
  { name: "Face Masks",   slug: "face-masks",   icon: "🌸", displayOrder: 4 },
  { name: "Cleansers",    slug: "cleansers",    icon: "🫧", displayOrder: 5 },
  { name: "Toners",       slug: "toners",       icon: "💦", displayOrder: 6 },
  { name: "Eye Care",     slug: "eye-care",     icon: "👁️", displayOrder: 7 },
  { name: "Lip Care",     slug: "lip-care",     icon: "💋", displayOrder: 8 },
  { name: "Hair Care",    slug: "hair-care",    icon: "💇", displayOrder: 9 },
];

const sampleProducts = [
  {
    name: "Hada Labo Gokujyun Premium Hyaluronic Acid Milk",
    slug: "hada-labo-gokujyun-premium-milk",
    description: "A deeply hydrating milk-type moisturizer designed for dehydrated, dry, and combination skin. The texture is richer than a lotion but lighter than a heavy cream, making it ideal for humid climates like Bangladesh.",
    category: "moisturizers",
    price: "1520",
    discountPrice: null,
    stock: 80,
    images: ["https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&q=90"],
    ingredients: "7 Types of Hyaluronic Acid, Squalane, Hydrolyzed Hyaluronic Acid, Sodium Hyaluronate",
    keyBenefits: ["Intense long-lasting hydration", "Strengthens moisture barrier", "Makes skin plump and smooth", "Helps reduce dehydration lines"],
    mainIngredients: [
      { name: "7 Types of Hyaluronic Acid", icon: "💧" },
      { name: "Squalane", icon: "🌿" },
      { name: "Hydrolyzed Hyaluronic Acid", icon: "💊" },
      { name: "Sodium Hyaluronate", icon: "🧬" },
    ],
    bestFor: ["Dry skin", "Dehydrated skin", "Sensitive skin"],
    texture: "Rich milky emulsion with non-greasy finish.",
    isFeatured: true,
  },
  {
    name: "Naturie Hatomugi Skin Conditioning Gel",
    slug: "naturie-hatomugi-skin-conditioning-gel",
    description: "A lightweight gel moisturizer famous for calming overheated and oily skin while delivering refreshing hydration.",
    category: "moisturizers",
    price: "1450",
    discountPrice: null,
    stock: 100,
    images: ["https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=600&q=90"],
    ingredients: "Job's Tears (Hatomugi) Extract, Glycerin, Vitamin E",
    keyBenefits: ["Soothes irritation and redness", "Lightweight hydration", "Cooling effect", "Non-sticky finish"],
    mainIngredients: [
      { name: "Job's Tears (Hatomugi) Extract", icon: "🌾" },
      { name: "Glycerin", icon: "💧" },
      { name: "Vitamin E", icon: "🌻" },
    ],
    bestFor: ["Oily skin", "Combination skin", "Acne-prone skin"],
    texture: "Water-gel texture with fast absorption.",
    isFeatured: true,
  },
  {
    name: "Curel Intensive Moisture Facial Cream",
    slug: "curel-intensive-moisture-facial-cream",
    description: "A dermatologist-loved ceramide cream developed for extremely dry and sensitive skin.",
    category: "moisturizers",
    price: "2400",
    discountPrice: null,
    stock: 60,
    images: ["https://images.unsplash.com/photo-1567225557594-88d73e55f2cb?w=600&q=90"],
    ingredients: "Ceramides, Eucalyptus Extract, Glycerin",
    keyBenefits: ["Repairs damaged skin barrier", "Deeply moisturizes without heaviness", "Reduces irritation and dryness", "Fragrance-free and alcohol-free"],
    mainIngredients: [
      { name: "Ceramides", icon: "🛡️" },
      { name: "Eucalyptus Extract", icon: "🌿" },
      { name: "Glycerin", icon: "💧" },
    ],
    bestFor: ["Sensitive skin", "Dry skin", "Barrier-damaged skin"],
    texture: "Soft cream with silky finish.",
    isFeatured: false,
  },
  {
    name: "Sana Nameraka Honpo Soy Milk Cream",
    slug: "sana-nameraka-honpo-soy-milk-cream",
    description: "A cult-favorite anti-aging moisturizer enriched with fermented soy milk.",
    category: "moisturizers",
    price: "1200",
    discountPrice: null,
    stock: 70,
    images: ["https://images.unsplash.com/photo-1585751119414-ef2636f8aede?w=600&q=90"],
    ingredients: "Fermented Soy Milk, Soy Isoflavones, Squalane",
    keyBenefits: ["Improves elasticity", "Makes skin bouncy and soft", "Hydrates deeply", "Helps fine lines"],
    mainIngredients: [
      { name: "Fermented Soy Milk", icon: "🥛" },
      { name: "Soy Isoflavones", icon: "🌱" },
      { name: "Squalane", icon: "🌿" },
    ],
    bestFor: ["Mature skin", "Dry skin", "Dull skin"],
    texture: "Rich creamy texture.",
    isFeatured: false,
  },
  {
    name: "Melano CC Brightening Gel",
    slug: "melano-cc-brightening-gel",
    description: "A brightening gel moisturizer targeting acne marks and uneven tone.",
    category: "moisturizers",
    price: "1500",
    discountPrice: null,
    stock: 90,
    images: ["https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600&q=90"],
    ingredients: "Vitamin C, Vitamin E, Dipotassium Glycyrrhizate",
    keyBenefits: ["Fades dark spots", "Brightens dull skin", "Lightweight hydration", "Controls excess oil"],
    mainIngredients: [
      { name: "Vitamin C", icon: "🍋" },
      { name: "Vitamin E", icon: "🌻" },
      { name: "Dipotassium Glycyrrhizate", icon: "🌿" },
    ],
    bestFor: ["Acne marks", "Oily skin", "Uneven tone"],
    texture: "Refreshing gel-cream.",
    isFeatured: false,
  },
  {
    name: "Melano CC Intensive Anti-Spot Essence",
    slug: "melano-cc-intensive-anti-spot-essence",
    description: "One of the most popular Japanese Vitamin C serums worldwide for hyperpigmentation and acne scars.",
    category: "serums",
    price: "1350",
    discountPrice: null,
    stock: 120,
    images: ["https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=600&q=90"],
    ingredients: "Pure Vitamin C (Ascorbic Acid), Vitamin E, Alpinia Extract",
    keyBenefits: ["Fades acne scars", "Reduces pigmentation", "Brightens complexion", "Antioxidant protection"],
    mainIngredients: [
      { name: "Pure Vitamin C (Ascorbic Acid)", icon: "🍋" },
      { name: "Vitamin E", icon: "🌻" },
      { name: "Alpinia Extract", icon: "🌺" },
    ],
    bestFor: ["Hyperpigmentation", "Acne marks", "Uneven tone"],
    texture: "Light oily essence that absorbs quickly.",
    isFeatured: true,
  },
  {
    name: "Shiseido Ultimune Power Infusing Concentrate",
    slug: "shiseido-ultimune-power-infusing-concentrate",
    description: "A luxury anti-aging serum focused on strengthening the skin's defense system.",
    category: "serums",
    price: "8500",
    discountPrice: null,
    stock: 30,
    images: ["https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600&q=90"],
    ingredients: "Reishi Mushroom Extract, Iris Root Extract, Ginkgo Biloba Leaf Extract",
    keyBenefits: ["Improves skin resilience", "Boosts glow", "Hydrates deeply", "Helps signs of aging"],
    mainIngredients: [
      { name: "Reishi Mushroom Extract", icon: "🍄" },
      { name: "Iris Root Extract", icon: "🌸" },
      { name: "Ginkgo Biloba Leaf Extract", icon: "🍃" },
    ],
    bestFor: ["Mature skin", "Dull skin", "Dry skin"],
    texture: "Silky lightweight serum.",
    isFeatured: true,
  },
  {
    name: "Hada Labo Gokujyun Aging Care Essence",
    slug: "hada-labo-gokujyun-aging-care-essence",
    description: "An affordable anti-aging essence combining brightening and hydration.",
    category: "serums",
    price: "2000",
    discountPrice: null,
    stock: 75,
    images: ["https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&q=90"],
    ingredients: "Niacinamide, Hyaluronic Acid, Collagen",
    keyBenefits: ["Firms skin", "Brightens complexion", "Deep hydration", "Helps fine lines"],
    mainIngredients: [
      { name: "Niacinamide", icon: "✨" },
      { name: "Hyaluronic Acid", icon: "💧" },
      { name: "Collagen", icon: "🧬" },
    ],
    bestFor: ["Aging skin", "Dehydrated skin", "Dull skin"],
    texture: "Hydrating essence.",
    isFeatured: false,
  },
  {
    name: "Skin Aqua Hyaluronic Serum UV Sunscreen Gel",
    slug: "skin-aqua-hyaluronic-serum-uv-gel",
    description: "A hybrid morning product combining serum hydration with UV protection.",
    category: "serums",
    price: "1440",
    discountPrice: null,
    stock: 85,
    images: ["https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=600&q=90"],
    ingredients: "Hyaluronic Acid, Collagen, SPF Filters",
    keyBenefits: ["UV protection", "Hydration boost", "No white cast", "Lightweight finish"],
    mainIngredients: [
      { name: "Hyaluronic Acid", icon: "💧" },
      { name: "Collagen", icon: "🧬" },
      { name: "SPF Filters", icon: "☀️" },
    ],
    bestFor: ["Daily morning routine", "Oily skin", "Combination skin"],
    texture: "Watery gel serum.",
    isFeatured: false,
  },
  {
    name: "Bioré UV Aqua Rich Watery Essence SPF 50+",
    slug: "biore-uv-aqua-rich-watery-essence-spf50",
    description: "One of the most famous Japanese sunscreens because of its invisible watery finish.",
    category: "sunscreen",
    price: "1380",
    discountPrice: null,
    stock: 150,
    images: ["https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=600&q=90"],
    ingredients: "Hyaluronic Acid, Royal Jelly Extract, UV Filters",
    keyBenefits: ["SPF 50+ PA++++ protection", "No white cast", "Sweat-resistant", "Works well under makeup"],
    mainIngredients: [
      { name: "Hyaluronic Acid", icon: "💧" },
      { name: "Royal Jelly Extract", icon: "🍯" },
      { name: "UV Filters", icon: "☀️" },
    ],
    bestFor: ["Oily skin", "Humid weather", "Everyday use"],
    texture: "Ultra-light watery essence.",
    isFeatured: true,
  },
  {
    name: "Anessa Perfect UV Sunscreen Skincare Milk",
    slug: "anessa-perfect-uv-sunscreen-skincare-milk",
    description: "A premium sunscreen known for exceptional durability in hot climates.",
    category: "sunscreen",
    price: "2990",
    discountPrice: null,
    stock: 60,
    images: ["https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600&q=90"],
    ingredients: "Zinc Oxide, Titanium Dioxide, Beauty Sun Essence",
    keyBenefits: ["Strong UV protection", "Waterproof and sweatproof", "Long-lasting outdoor wear", "Protects against tanning"],
    mainIngredients: [
      { name: "Zinc Oxide", icon: "🛡️" },
      { name: "Titanium Dioxide", icon: "⚡" },
      { name: "Beauty Sun Essence", icon: "✨" },
    ],
    bestFor: ["Outdoor activities", "Sweaty weather", "Beach use"],
    texture: "Milky fluid texture.",
    isFeatured: false,
  },
  {
    name: "Nivea Sun Protect Super Water Gel",
    slug: "nivea-sun-protect-super-water-gel",
    description: "A lightweight daily sunscreen with a refreshing gel consistency.",
    category: "sunscreen",
    price: "1820",
    discountPrice: null,
    stock: 90,
    images: ["https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600&q=90"],
    ingredients: "Hyaluronic Acid, SPF Filters, Water-based hydrators",
    keyBenefits: ["Comfortable daily wear", "Hydrating feel", "No sticky residue", "Good for layering"],
    mainIngredients: [
      { name: "Hyaluronic Acid", icon: "💧" },
      { name: "SPF Filters", icon: "☀️" },
      { name: "Water-based hydrators", icon: "🌊" },
    ],
    bestFor: ["Daily indoor use", "Combination skin", "Sensitive skin"],
    texture: "Very thin watery gel.",
    isFeatured: false,
  },
  {
    name: "Senka Perfect Whip Cleansing Foam",
    slug: "senka-perfect-whip-cleansing-foam",
    description: "Japan's iconic foaming cleanser with dense micro-foam technology.",
    category: "cleansers",
    price: "1000",
    discountPrice: null,
    stock: 130,
    images: ["https://images.unsplash.com/photo-1585751119414-ef2636f8aede?w=600&q=90"],
    ingredients: "Silk Essence, Hyaluronic Acid, Glycerin",
    keyBenefits: ["Deep cleans pores", "Removes excess oil", "Rich foamy texture", "Leaves skin soft"],
    mainIngredients: [
      { name: "Silk Essence", icon: "🪶" },
      { name: "Hyaluronic Acid", icon: "💧" },
      { name: "Glycerin", icon: "💦" },
    ],
    bestFor: ["Oily skin", "Combination skin"],
    texture: "Dense creamy foam.",
    isFeatured: false,
  },
  {
    name: "Kose Softymo Speedy Cleansing Oil",
    slug: "kose-softymo-speedy-cleansing-oil",
    description: "A bestselling cleansing oil that melts waterproof makeup and sunscreen quickly.",
    category: "cleansers",
    price: "1650",
    discountPrice: null,
    stock: 70,
    images: ["https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=600&q=90"],
    ingredients: "Mineral Oil, Olive Oil, Jojoba Seed Oil",
    keyBenefits: ["Removes heavy makeup", "Dissolves sunscreen", "No harsh rubbing needed", "Can be used with wet hands"],
    mainIngredients: [
      { name: "Mineral Oil", icon: "🧴" },
      { name: "Olive Oil", icon: "🫒" },
      { name: "Jojoba Seed Oil", icon: "🌿" },
    ],
    bestFor: ["Makeup users", "Double cleansing"],
    texture: "Light silky oil.",
    isFeatured: false,
  },
  {
    name: "DHC Deep Cleansing Oil",
    slug: "dhc-deep-cleansing-oil",
    description: "A legendary Japanese oil cleanser with olive oil base.",
    category: "cleansers",
    price: "2200",
    discountPrice: null,
    stock: 55,
    images: ["https://images.unsplash.com/photo-1567225557594-88d73e55f2cb?w=600&q=90"],
    ingredients: "Olive Oil, Rosemary Leaf Oil, Vitamin E",
    keyBenefits: ["Deep pore cleansing", "Softens blackheads", "Nourishes skin", "Removes waterproof makeup"],
    mainIngredients: [
      { name: "Olive Oil", icon: "🫒" },
      { name: "Rosemary Leaf Oil", icon: "🌿" },
      { name: "Vitamin E", icon: "🌻" },
    ],
    bestFor: ["Dry skin", "Makeup removal", "Mature skin"],
    texture: "Rich cleansing oil.",
    isFeatured: false,
  },
  {
    name: "Hada Labo Gokujyun Hydrating Lotion",
    slug: "hada-labo-gokujyun-hydrating-lotion",
    description: "A highly hydrating toner-lotion hybrid that floods skin with moisture.",
    category: "toners",
    price: "1400",
    discountPrice: null,
    stock: 110,
    images: ["https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=600&q=90"],
    ingredients: "Multiple Hyaluronic Acids, Glycerin",
    keyBenefits: ["Deep hydration", "Softens skin texture", "Preps skin for skincare", "Minimal ingredient formula"],
    mainIngredients: [
      { name: "Multiple Hyaluronic Acids", icon: "💧" },
      { name: "Glycerin", icon: "💦" },
    ],
    bestFor: ["Dry skin", "Sensitive skin", "Dehydrated skin"],
    texture: "Slightly thick watery lotion.",
    isFeatured: true,
  },
  {
    name: "Kikumasamune High Moist Sake Lotion",
    slug: "kikumasamune-high-moist-sake-lotion",
    description: "A huge-value toner enriched with sake ferment for brightening and hydration.",
    category: "toners",
    price: "1800",
    discountPrice: null,
    stock: 65,
    images: ["https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600&q=90"],
    ingredients: "Sake Ferment, Ceramides, Amino Acids, Arbutin",
    keyBenefits: ["Brightens dull skin", "Deep hydration", "Softens rough texture", "Multi-use toner"],
    mainIngredients: [
      { name: "Sake Ferment", icon: "🍶" },
      { name: "Ceramides", icon: "🛡️" },
      { name: "Amino Acids", icon: "🧬" },
      { name: "Arbutin", icon: "🌿" },
    ],
    bestFor: ["Dry skin", "Body hydration", "Dull skin"],
    texture: "Milky watery toner.",
    isFeatured: false,
  },
  {
    name: "Lululun Pure Every Day Mask",
    slug: "lululun-pure-every-day-mask",
    description: "Premium daily sheet masks focused on maintaining skin hydration and balance.",
    category: "face-masks",
    price: "1200",
    discountPrice: null,
    stock: 100,
    images: ["https://images.unsplash.com/photo-1585751119414-ef2636f8aede?w=600&q=90"],
    ingredients: "Seaweed Extract, Hyaluronic Acid, Glycerin",
    keyBenefits: ["Daily hydration", "Improves softness", "Refreshes tired skin", "Supports skin barrier"],
    mainIngredients: [
      { name: "Seaweed Extract", icon: "🌊" },
      { name: "Hyaluronic Acid", icon: "💧" },
      { name: "Glycerin", icon: "💦" },
    ],
    bestFor: ["Daily use", "Dehydrated skin"],
    texture: "Soft essence-soaked cotton sheet.",
    isFeatured: false,
  },
  {
    name: "Nadeshiko Keana Rice Mask",
    slug: "nadeshiko-keana-rice-mask",
    description: "A cult-favorite pore care mask enriched with Japanese rice extracts.",
    category: "face-masks",
    price: "1500",
    discountPrice: null,
    stock: 80,
    images: ["https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=600&q=90"],
    ingredients: "Rice Ferment Extract, Rice Bran Oil, Rice Ceramides",
    keyBenefits: ["Minimizes pores", "Smooths rough skin", "Brightens complexion", "Hydrates deeply"],
    mainIngredients: [
      { name: "Rice Ferment Extract", icon: "🍚" },
      { name: "Rice Bran Oil", icon: "🌾" },
      { name: "Rice Ceramides", icon: "🛡️" },
    ],
    bestFor: ["Large pores", "Rough texture", "Dull skin"],
    texture: "Creamy wash-off mask.",
    isFeatured: false,
  },
  {
    name: "Sana Nameraka Honpo Soy Milk Wrinkle Eye Cream",
    slug: "sana-nameraka-honpo-soy-milk-wrinkle-eye-cream",
    description: "A gentle eye cream focused on hydration and wrinkle prevention.",
    category: "eye-care",
    price: "1190",
    discountPrice: null,
    stock: 45,
    images: ["https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&q=90"],
    ingredients: "Soy Isoflavones, Retinol Derivative, Vitamin E",
    keyBenefits: ["Smooths fine lines", "Reduces dryness", "Improves elasticity", "Gentle formula"],
    mainIngredients: [
      { name: "Soy Isoflavones", icon: "🌱" },
      { name: "Retinol Derivative", icon: "✨" },
      { name: "Vitamin E", icon: "🌻" },
    ],
    bestFor: ["Fine lines", "Dry under-eyes"],
    texture: "Soft creamy texture.",
    isFeatured: false,
  },
  {
    name: "DHC Lip Cream",
    slug: "dhc-lip-cream",
    description: "An award-winning lip balm with nourishing botanical oils.",
    category: "lip-care",
    price: "950",
    discountPrice: null,
    stock: 200,
    images: ["https://images.unsplash.com/photo-1567225557594-88d73e55f2cb?w=600&q=90"],
    ingredients: "Olive Oil, Aloe Vera, Vitamin E, Licorice Extract",
    keyBenefits: ["Repairs cracked lips", "Long-lasting moisture", "Smooth finish", "Protects lips from dryness"],
    mainIngredients: [
      { name: "Olive Oil", icon: "🫒" },
      { name: "Aloe Vera", icon: "🌵" },
      { name: "Vitamin E", icon: "🌻" },
      { name: "Licorice Extract", icon: "🌿" },
    ],
    bestFor: ["Dry lips", "Chapped lips"],
    texture: "Smooth balm stick.",
    isFeatured: false,
  },
  {
    name: "Shiseido Fino Premium Touch Hair Mask",
    slug: "shiseido-fino-premium-touch-hair-mask",
    description: "A viral Japanese hair mask famous for transforming dry, damaged hair.",
    category: "hair-care",
    price: "1599",
    discountPrice: null,
    stock: 70,
    images: ["https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&q=90"],
    ingredients: "Royal Jelly EX, PCA, Lipidure EX, Squalane",
    keyBenefits: ["Repairs damaged hair", "Makes hair silky smooth", "Reduces frizz", "Adds shine"],
    mainIngredients: [
      { name: "Royal Jelly EX", icon: "🍯" },
      { name: "PCA", icon: "🧬" },
      { name: "Lipidure EX", icon: "💧" },
      { name: "Squalane", icon: "🌿" },
    ],
    bestFor: ["Chemically treated hair", "Dry hair", "Frizzy hair"],
    texture: "Rich creamy mask.",
    isFeatured: true,
  },
  {
    name: "&honey Deep Moist Hair Oil",
    slug: "honey-deep-moist-hair-oil",
    description: "A premium honey-based hair oil designed for moisture retention and glossy shine.",
    category: "hair-care",
    price: "2200",
    discountPrice: null,
    stock: 50,
    images: ["https://images.unsplash.com/photo-1622470953794-aa9c70b0fb9d?w=600&q=90"],
    ingredients: "Honey, Argan Oil, Royal Jelly, Keratin",
    keyBenefits: ["Deep hydration", "Controls frizz", "Heat protection", "Glossy finish"],
    mainIngredients: [
      { name: "Honey", icon: "🍯" },
      { name: "Argan Oil", icon: "🌰" },
      { name: "Royal Jelly", icon: "👑" },
      { name: "Keratin", icon: "🧬" },
    ],
    bestFor: ["Dry hair", "Curly hair", "Frizzy hair"],
    texture: "Light nourishing oil.",
    isFeatured: false,
  },
];

const sampleCoupons = [
  {
    code: "WELCOME20",
    discountType: "percentage",
    discountValue: "20",
    minOrderAmount: "1000",
    expiryDate: new Date("2026-12-31"),
    isActive: true,
  },
  {
    code: "SAKURA500",
    discountType: "fixed",
    discountValue: "500",
    minOrderAmount: "3000",
    expiryDate: new Date("2026-12-31"),
    isActive: true,
  },
];

async function seed() {
  console.log("Seeding database...");

  const existingCategories = await db.select().from(categories);
  if (existingCategories.length === 0) {
    await db.insert(categories).values(sampleCategories);
    console.log(`Inserted ${sampleCategories.length} categories`);
  } else {
    for (const cat of sampleCategories) {
      try {
        await db.insert(categories).values(cat).onConflictDoNothing();
      } catch (_) {}
    }
    console.log("Categories seeded (skipped existing)");
  }

  const existingProducts = await db.select().from(products);
  if (existingProducts.length === 0) {
    await db.insert(products).values(sampleProducts as any);
    console.log(`Inserted ${sampleProducts.length} products`);
  } else {
    console.log(`Products already exist (${existingProducts.length}), skipping`);
  }

  const existingCoupons = await db.select().from(coupons);
  if (existingCoupons.length === 0) {
    await db.insert(coupons).values(sampleCoupons);
    console.log(`Inserted ${sampleCoupons.length} coupons`);
  } else {
    console.log(`Coupons already exist, skipping`);
  }

  console.log("Seed complete!");
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
